### ISSUE TITLE
Where are the results?

### ISSUE THREAD

**Issue by ghost** [litesolutions/objectscriptquality-community#2]
the links in Readme lead to some LOGIN.
but no public user / password is provided.
_SYSTEM / SYS doesn't work

**Comment by dtamajon** [comment]
The link takes to main SonarQube page where you can see briefly the number of projects and issues. If you click on the projects number or in the tab "Projects" on the menu, you are taken to the list of all projects analyzed.

**Comment by ghost** [comment]
Ah!  Thanks for the clarification. It wasn't that obvious
